# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Spot < Formula
  desc "Spot — CLI for restaurant reservation searches and bookings."
  homepage "https://github.com/spot-nyc/spot"
  version "0.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/spot-nyc/spot/releases/download/v0.4.0/spot_0.4.0_darwin_amd64.tar.gz"
      sha256 "e2a6dda90b99f7da8e11720d95677e142cfc0a21b8f0d2c96d6723055a0e3c6e"

      define_method(:install) do
        bin.install "spot"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/spot-nyc/spot/releases/download/v0.4.0/spot_0.4.0_darwin_arm64.tar.gz"
      sha256 "9166f5d75f79ab32ab5b9723c3c37826a85c09e271fd106b0944177a0bd453d7"

      define_method(:install) do
        bin.install "spot"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/spot-nyc/spot/releases/download/v0.4.0/spot_0.4.0_linux_amd64.tar.gz"
      sha256 "2dee27f7343cb5632e0ba6f696aa427a6204815639f080dba8e2d9dea856d5a7"
      define_method(:install) do
        bin.install "spot"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/spot-nyc/spot/releases/download/v0.4.0/spot_0.4.0_linux_arm64.tar.gz"
      sha256 "70bc287eaac0d97198cfe6be547f3d8afaabba96513da112aac8b049b02e0cf2"
      define_method(:install) do
        bin.install "spot"
      end
    end
  end

  test do
    system "#{bin}/spot --version"
  end
end
