# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Spot < Formula
  desc "Spot — CLI for restaurant reservation searches and bookings."
  homepage "https://github.com/spot-nyc/spot"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/spot-nyc/spot/releases/download/v0.1.0/spot_0.1.0_darwin_amd64.tar.gz"
      sha256 "d4e893fa09d25d7443ea04aae602dd0c3a9f38507f091aca207a371c07f4232e"

      define_method(:install) do
        bin.install "spot"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/spot-nyc/spot/releases/download/v0.1.0/spot_0.1.0_darwin_arm64.tar.gz"
      sha256 "3d6dc86d5c5cd85fbd142813d0d457292dda601e0407cdbe82677ed379ef6200"

      define_method(:install) do
        bin.install "spot"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/spot-nyc/spot/releases/download/v0.1.0/spot_0.1.0_linux_amd64.tar.gz"
      sha256 "b4410b9412c5b038f5afd986a917b2a745233239272ca13d3e66580efa020194"
      define_method(:install) do
        bin.install "spot"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/spot-nyc/spot/releases/download/v0.1.0/spot_0.1.0_linux_arm64.tar.gz"
      sha256 "080431845673b073ae193b7b07c022136619623521eaa05b908ee9c0aee9b4e2"
      define_method(:install) do
        bin.install "spot"
      end
    end
  end

  test do
    system "#{bin}/spot --version"
  end
end
